api_platform:
    title: '(Re)ssources Relationnelles API'
    description: 'Symfony API to manage Ressources relationnelles app'
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
